/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UndangRouteImport } from './routes/undang'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PendampingRouteImport } from './routes/pendamping'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PendampingChildIdRouteImport } from './routes/pendamping.$childId'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'

const UndangRoute = UndangRouteImport.update({
  id: '/undang',
  path: '/undang',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PendampingRoute = PendampingRouteImport.update({
  id: '/pendamping',
  path: '/pendamping',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PendampingChildIdRoute = PendampingChildIdRouteImport.update({
  id: '/$childId',
  path: '/$childId',
  getParentRoute: () => PendampingRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pendamping': typeof PendampingRouteWithChildren
  '/signup': typeof SignupRoute
  '/undang': typeof UndangRoute
  '/invite/$token': typeof InviteTokenRoute
  '/pendamping/$childId': typeof PendampingChildIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pendamping': typeof PendampingRouteWithChildren
  '/signup': typeof SignupRoute
  '/undang': typeof UndangRoute
  '/invite/$token': typeof InviteTokenRoute
  '/pendamping/$childId': typeof PendampingChildIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pendamping': typeof PendampingRouteWithChildren
  '/signup': typeof SignupRoute
  '/undang': typeof UndangRoute
  '/invite/$token': typeof InviteTokenRoute
  '/pendamping/$childId': typeof PendampingChildIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/pendamping'
    | '/signup'
    | '/undang'
    | '/invite/$token'
    | '/pendamping/$childId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/pendamping'
    | '/signup'
    | '/undang'
    | '/invite/$token'
    | '/pendamping/$childId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/pendamping'
    | '/signup'
    | '/undang'
    | '/invite/$token'
    | '/pendamping/$childId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PendampingRoute: typeof PendampingRouteWithChildren
  SignupRoute: typeof SignupRoute
  UndangRoute: typeof UndangRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/undang': {
      id: '/undang'
      path: '/undang'
      fullPath: '/undang'
      preLoaderRoute: typeof UndangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pendamping': {
      id: '/pendamping'
      path: '/pendamping'
      fullPath: '/pendamping'
      preLoaderRoute: typeof PendampingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pendamping/$childId': {
      id: '/pendamping/$childId'
      path: '/$childId'
      fullPath: '/pendamping/$childId'
      preLoaderRoute: typeof PendampingChildIdRouteImport
      parentRoute: typeof PendampingRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PendampingRouteChildren {
  PendampingChildIdRoute: typeof PendampingChildIdRoute
}

const PendampingRouteChildren: PendampingRouteChildren = {
  PendampingChildIdRoute: PendampingChildIdRoute,
}

const PendampingRouteWithChildren = PendampingRoute._addFileChildren(
  PendampingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PendampingRoute: PendampingRouteWithChildren,
  SignupRoute: SignupRoute,
  UndangRoute: UndangRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
